export const WME_REPOSITORY_NAMES = [
  'bigJunctions',
  'cities',
  'countries',
  'editSuggestions',
  'junctions',
  'majorTrafficEvents',
  'managedAreas',
  'mapComments',
  'mapProblems',
  'mapUpdateRequests',
  'nodes',
  'onlineEditors',
  'permanentHazards',
  'problemDetails',
  'restrictedDrivingAreas',
  'restrictedEditingAreas',
  'roadClosures',
  'schedules',
  'segments',
  'segmentHouseNumbers',
  'segmentSuggestions',
  'signTypes',
  'states',
  'streets',
  'turnClosures',
  'updateRequestSessions',
  'users',
  'userAreas',
  'venues',
] as const;
export type WmeRepositoryName = typeof WME_REPOSITORY_NAMES[number];
